baseUrl = "http://golangshow.com/"
languageCode = "ru-RU"
title = "Подкаст GolangShow"
theme = "golangshow"
paginate = 20
disqusShortname = "golangshow"
copyright = "All rights reserved - 2015-2016"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
  truncate = false

  tagline = "Русскоязычный подкаст о Go"
  defaultKeywords = "Go,golang,подкаст"
  # cover = "/images/cover.png"
  logo = "/images/logo2.png"
  theme = "theme-base-0d"

  home = "Главная"

  googleAnalytics = "UA-65258742-1"
  github = "https://github.com/GolangShow/golangshow.com"
  twitter = "https://twitter.com/golangshow"
  vk = "https://vk.com/golangshow"
  facebook = "https://www.facebook.com/golangshow"
  rss = true

[[menu.main]]
  name = "Онлайн вещание"
  weight = -100
  identifier = "online"
  url = "/online"

[[menu.main]]
  name = "Гости"
  weight = 10
  identifier = "guests"
  url = "/categories/гости"

[[menu.main]]
  name = "iTunes"
  weight = 10
  identifier = "itunes"
  url = "https://itunes.apple.com/ru/podcast/podkast-golangshow/id1031101295?l=en&mt=2"
[[menu.main]]
  name = "Поддержать подкаст"
  identifier = "patreon"
  url = "https://www.patreon.com/golangshow"

[[menu.friends]]
  name = "4gophers.ru"
  identifier = "4gophers"
  url = "http://4gophers.ru"

[[menu.friends]]
  name = "DigitalOcean"
  ideantifier = "digitalocean"
  url = "https://www.digitalocean.com/?utm_campaign=golangshow&utm_medium=podcast&refcode=63eedb038a3e"
